--DROP TABLE adv_product;
--select * from adv_product;
CREATE TABLE adv_product(
	ProductID int NOT NULL,
	Name nvarchar2(100) NOT NULL,
	Color nvarchar2(15) NULL,
	SafetyStockLevel int NOT NULL,
	ListPrice number(10,4) NOT NULL,
	ProductSubcategoryID int NULL
);

--
INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (1, N'Adjustable Race', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (2, N'Bearing Ball', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (3, N'BB Ball Bearing', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (4, N'Headset Ball Bearings', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (316, N'Blade', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (317, N'LL Crankarm', N'Black', 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (318, N'ML Crankarm', N'Black', 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (319, N'HL Crankarm', N'Black', 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (320, N'Chainring Bolts', N'Silver', 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (321, N'Chainring Nut', N'Silver', 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (322, N'Chainring', N'Black', 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (323, N'Crown Race', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (324, N'Chain Stays', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (325, N'Decal 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (326, N'Decal 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (327, N'Down Tube', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (328, N'Mountain End Caps', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (329, N'Road End Caps', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (330, N'Touring End Caps', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (331, N'Fork End', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (332, N'Freewheel', N'Silver', 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (341, N'Flat Washer 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (342, N'Flat Washer 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (343, N'Flat Washer 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (344, N'Flat Washer 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (345, N'Flat Washer 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (346, N'Flat Washer 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (347, N'Flat Washer 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (348, N'Flat Washer 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (349, N'Flat Washer 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (350, N'Fork Crown', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (351, N'Front Derailleur Cage', N'Silver', 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (352, N'Front Derailleur Linkage', N'Silver', 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (355, N'Guide Pulley', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (356, N'LL Grip Tape', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (357, N'ML Grip Tape', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (358, N'HL Grip Tape', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (359, N'Thin-Jam Hex Nut 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (360, N'Thin-Jam Hex Nut 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (361, N'Thin-Jam Hex Nut 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (362, N'Thin-Jam Hex Nut 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (363, N'Thin-Jam Hex Nut 15', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (364, N'Thin-Jam Hex Nut 16', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (365, N'Thin-Jam Hex Nut 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (366, N'Thin-Jam Hex Nut 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (367, N'Thin-Jam Hex Nut 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (368, N'Thin-Jam Hex Nut 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (369, N'Thin-Jam Hex Nut 13', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (370, N'Thin-Jam Hex Nut 14', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (371, N'Thin-Jam Hex Nut 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (372, N'Thin-Jam Hex Nut 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (373, N'Thin-Jam Hex Nut 12', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (374, N'Thin-Jam Hex Nut 11', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (375, N'Hex Nut 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (376, N'Hex Nut 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (377, N'Hex Nut 16', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (378, N'Hex Nut 17', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (379, N'Hex Nut 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (380, N'Hex Nut 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (381, N'Hex Nut 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (382, N'Hex Nut 22', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (383, N'Hex Nut 23', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (384, N'Hex Nut 12', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (385, N'Hex Nut 13', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (386, N'Hex Nut 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (387, N'Hex Nut 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (388, N'Hex Nut 11', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (389, N'Hex Nut 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (390, N'Hex Nut 20', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (391, N'Hex Nut 21', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (392, N'Hex Nut 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (393, N'Hex Nut 14', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (394, N'Hex Nut 15', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (395, N'Hex Nut 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (396, N'Hex Nut 18', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (397, N'Hex Nut 19', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (398, N'Handlebar Tube', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (399, N'Head Tube', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (400, N'LL Hub', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (401, N'HL Hub', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (402, N'Keyed Washer', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (403, N'External Lock Washer 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (404, N'External Lock Washer 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (405, N'External Lock Washer 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (406, N'External Lock Washer 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (407, N'External Lock Washer 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (408, N'External Lock Washer 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (409, N'External Lock Washer 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (410, N'External Lock Washer 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (411, N'External Lock Washer 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (412, N'Internal Lock Washer 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (413, N'Internal Lock Washer 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (414, N'Internal Lock Washer 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (415, N'Internal Lock Washer 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (416, N'Internal Lock Washer 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (417, N'Internal Lock Washer 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (418, N'Internal Lock Washer 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (419, N'Internal Lock Washer 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (420, N'Internal Lock Washer 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (421, N'Internal Lock Washer 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (422, N'Thin-Jam Lock Nut 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (423, N'Thin-Jam Lock Nut 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (424, N'Thin-Jam Lock Nut 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (425, N'Thin-Jam Lock Nut 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (426, N'Thin-Jam Lock Nut 15', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (427, N'Thin-Jam Lock Nut 16', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (428, N'Thin-Jam Lock Nut 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (429, N'Thin-Jam Lock Nut 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (430, N'Thin-Jam Lock Nut 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (431, N'Thin-Jam Lock Nut 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (432, N'Thin-Jam Lock Nut 13', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (433, N'Thin-Jam Lock Nut 14', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (434, N'Thin-Jam Lock Nut 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (435, N'Thin-Jam Lock Nut 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (436, N'Thin-Jam Lock Nut 12', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (437, N'Thin-Jam Lock Nut 11', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (438, N'Lock Nut 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (439, N'Lock Nut 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (440, N'Lock Nut 16', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (441, N'Lock Nut 17', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (442, N'Lock Nut 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (443, N'Lock Nut 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (444, N'Lock Nut 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (445, N'Lock Nut 22', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (446, N'Lock Nut 23', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (447, N'Lock Nut 12', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (448, N'Lock Nut 13', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (449, N'Lock Nut 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (450, N'Lock Nut 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (451, N'Lock Nut 11', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (452, N'Lock Nut 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (453, N'Lock Nut 20', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (454, N'Lock Nut 21', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (455, N'Lock Nut 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (456, N'Lock Nut 14', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (457, N'Lock Nut 15', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (458, N'Lock Nut 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (459, N'Lock Nut 19', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (460, N'Lock Nut 18', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (461, N'Lock Ring', N'Silver', 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (462, N'Lower Head Race', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (463, N'Lock Washer 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (464, N'Lock Washer 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (465, N'Lock Washer 10', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (466, N'Lock Washer 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (467, N'Lock Washer 13', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (468, N'Lock Washer 8', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (469, N'Lock Washer 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (470, N'Lock Washer 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (471, N'Lock Washer 12', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (472, N'Lock Washer 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (473, N'Lock Washer 9', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (474, N'Lock Washer 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (475, N'Lock Washer 11', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (476, N'Metal Angle', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (477, N'Metal Bar 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (478, N'Metal Bar 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (479, N'Metal Plate 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (480, N'Metal Plate 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (481, N'Metal Plate 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (482, N'Metal Sheet 2', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (483, N'Metal Sheet 3', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (484, N'Metal Sheet 7', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (485, N'Metal Sheet 4', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (486, N'Metal Sheet 5', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (487, N'Metal Sheet 6', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (488, N'Metal Sheet 1', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (489, N'Metal Tread Plate', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (490, N'LL Nipple', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (491, N'HL Nipple', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (492, N'Paint - Black', NULL, 60, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (493, N'Paint - Red', NULL, 60, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (494, N'Paint - Silver', NULL, 60, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (495, N'Paint - Blue', NULL, 60, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (496, N'Paint - Yellow', NULL, 60, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (497, N'Pinch Bolt', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (504, N'Cup-Shaped Race', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (505, N'Cone-Shaped Race', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (506, N'Reflector', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (507, N'LL Mountain Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (508, N'ML Mountain Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (509, N'HL Mountain Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (510, N'LL Road Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (511, N'ML Road Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (512, N'HL Road Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (513, N'Touring Rim', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (514, N'LL Mountain Seat Assembly', NULL, 500, 133.3400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (515, N'ML Mountain Seat Assembly', NULL, 500, 147.1400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (516, N'HL Mountain Seat Assembly', NULL, 500, 196.9200, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (517, N'LL Road Seat Assembly', NULL, 500, 133.3400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (518, N'ML Road Seat Assembly', NULL, 500, 147.1400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (519, N'HL Road Seat Assembly', NULL, 500, 196.9200, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (520, N'LL Touring Seat Assembly', NULL, 500, 133.3400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (521, N'ML Touring Seat Assembly', NULL, 500, 147.1400, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (522, N'HL Touring Seat Assembly', NULL, 500, 196.9200, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (523, N'LL Spindle/Axle', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (524, N'HL Spindle/Axle', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (525, N'LL Shell', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (526, N'HL Shell', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (527, N'Spokes', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (528, N'Seat Lug', NULL, 1000, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (529, N'Stem', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (530, N'Seat Post', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (531, N'Steerer', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (532, N'Seat Stays', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (533, N'Seat Tube', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (534, N'Top Tube', NULL, 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (535, N'Tension Pulley', NULL, 800, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (679, N'Rear Derailleur Cage', N'Silver', 500, 0.0000, NULL)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (680, N'HL Road Frame - Black, 58', N'Black', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (706, N'HL Road Frame - Red, 58', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (707, N'Sport-100 Helmet, Red', N'Red', 4, 34.9900, 31)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (708, N'Sport-100 Helmet, Black', N'Black', 4, 34.9900, 31)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (709, N'Mountain Bike Socks, M', N'White', 4, 9.5000, 23)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (710, N'Mountain Bike Socks, L', N'White', 4, 9.5000, 23)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (711, N'Sport-100 Helmet, Blue', N'Blue', 4, 34.9900, 31)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (712, N'AWC Logo Cap', N'Multi', 4, 8.9900, 19)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (713, N'Long-Sleeve Logo Jersey, S', N'Multi', 4, 49.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (714, N'Long-Sleeve Logo Jersey, M', N'Multi', 4, 49.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (715, N'Long-Sleeve Logo Jersey, L', N'Multi', 4, 49.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (716, N'Long-Sleeve Logo Jersey, XL', N'Multi', 4, 49.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (717, N'HL Road Frame - Red, 62', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (718, N'HL Road Frame - Red, 44', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (719, N'HL Road Frame - Red, 48', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (720, N'HL Road Frame - Red, 52', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (721, N'HL Road Frame - Red, 56', N'Red', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (722, N'LL Road Frame - Black, 58', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (723, N'LL Road Frame - Black, 60', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (724, N'LL Road Frame - Black, 62', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (725, N'LL Road Frame - Red, 44', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (726, N'LL Road Frame - Red, 48', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (727, N'LL Road Frame - Red, 52', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (728, N'LL Road Frame - Red, 58', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (729, N'LL Road Frame - Red, 60', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (730, N'LL Road Frame - Red, 62', N'Red', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (731, N'ML Road Frame - Red, 44', N'Red', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (732, N'ML Road Frame - Red, 48', N'Red', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (733, N'ML Road Frame - Red, 52', N'Red', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (734, N'ML Road Frame - Red, 58', N'Red', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (735, N'ML Road Frame - Red, 60', N'Red', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (736, N'LL Road Frame - Black, 44', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (737, N'LL Road Frame - Black, 48', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (738, N'LL Road Frame - Black, 52', N'Black', 500, 337.2200, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (739, N'HL Mountain Frame - Silver, 42', N'Silver', 500, 1364.5000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (740, N'HL Mountain Frame - Silver, 44', N'Silver', 500, 1364.5000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (741, N'HL Mountain Frame - Silver, 48', N'Silver', 500, 1364.5000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (742, N'HL Mountain Frame - Silver, 46', N'Silver', 500, 1364.5000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (743, N'HL Mountain Frame - Black, 42', N'Black', 500, 1349.6000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (744, N'HL Mountain Frame - Black, 44', N'Black', 500, 1349.6000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (745, N'HL Mountain Frame - Black, 48', N'Black', 500, 1349.6000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (746, N'HL Mountain Frame - Black, 46', N'Black', 500, 1349.6000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (747, N'HL Mountain Frame - Black, 38', N'Black', 500, 1349.6000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (748, N'HL Mountain Frame - Silver, 38', N'Silver', 500, 1364.5000, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (749, N'Road-150 Red, 62', N'Red', 100, 3578.2700, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (750, N'Road-150 Red, 44', N'Red', 100, 3578.2700, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (751, N'Road-150 Red, 48', N'Red', 100, 3578.2700, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (752, N'Road-150 Red, 52', N'Red', 100, 3578.2700, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (753, N'Road-150 Red, 56', N'Red', 100, 3578.2700, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (754, N'Road-450 Red, 58', N'Red', 100, 1457.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (755, N'Road-450 Red, 60', N'Red', 100, 1457.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (756, N'Road-450 Red, 44', N'Red', 100, 1457.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (757, N'Road-450 Red, 48', N'Red', 100, 1457.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (758, N'Road-450 Red, 52', N'Red', 100, 1457.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (759, N'Road-650 Red, 58', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (760, N'Road-650 Red, 60', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (761, N'Road-650 Red, 62', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (762, N'Road-650 Red, 44', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (763, N'Road-650 Red, 48', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (764, N'Road-650 Red, 52', N'Red', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (765, N'Road-650 Black, 58', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (766, N'Road-650 Black, 60', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (767, N'Road-650 Black, 62', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (768, N'Road-650 Black, 44', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (769, N'Road-650 Black, 48', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (770, N'Road-650 Black, 52', N'Black', 100, 782.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (771, N'Mountain-100 Silver, 38', N'Silver', 100, 3399.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (772, N'Mountain-100 Silver, 42', N'Silver', 100, 3399.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (773, N'Mountain-100 Silver, 44', N'Silver', 100, 3399.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (774, N'Mountain-100 Silver, 48', N'Silver', 100, 3399.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (775, N'Mountain-100 Black, 38', N'Black', 100, 3374.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (776, N'Mountain-100 Black, 42', N'Black', 100, 3374.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (777, N'Mountain-100 Black, 44', N'Black', 100, 3374.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (778, N'Mountain-100 Black, 48', N'Black', 100, 3374.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (779, N'Mountain-200 Silver, 38', N'Silver', 100, 2319.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (780, N'Mountain-200 Silver, 42', N'Silver', 100, 2319.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (781, N'Mountain-200 Silver, 46', N'Silver', 100, 2319.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (782, N'Mountain-200 Black, 38', N'Black', 100, 2294.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (783, N'Mountain-200 Black, 42', N'Black', 100, 2294.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (784, N'Mountain-200 Black, 46', N'Black', 100, 2294.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (785, N'Mountain-300 Black, 38', N'Black', 100, 1079.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (786, N'Mountain-300 Black, 40', N'Black', 100, 1079.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (787, N'Mountain-300 Black, 44', N'Black', 100, 1079.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (788, N'Mountain-300 Black, 48', N'Black', 100, 1079.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (789, N'Road-250 Red, 44', N'Red', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (790, N'Road-250 Red, 48', N'Red', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (791, N'Road-250 Red, 52', N'Red', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (792, N'Road-250 Red, 58', N'Red', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (793, N'Road-250 Black, 44', N'Black', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (794, N'Road-250 Black, 48', N'Black', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (795, N'Road-250 Black, 52', N'Black', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (796, N'Road-250 Black, 58', N'Black', 100, 2443.3500, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (797, N'Road-550-W Yellow, 38', N'Yellow', 100, 1120.4900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (798, N'Road-550-W Yellow, 40', N'Yellow', 100, 1120.4900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (799, N'Road-550-W Yellow, 42', N'Yellow', 100, 1120.4900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (800, N'Road-550-W Yellow, 44', N'Yellow', 100, 1120.4900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (801, N'Road-550-W Yellow, 48', N'Yellow', 100, 1120.4900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (802, N'LL Fork', NULL, 500, 148.2200, 10)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (803, N'ML Fork', NULL, 500, 175.4900, 10)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (804, N'HL Fork', NULL, 500, 229.4900, 10)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (805, N'LL Headset', NULL, 500, 34.2000, 11)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (806, N'ML Headset', NULL, 500, 102.2900, 11)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (807, N'HL Headset', NULL, 500, 124.7300, 11)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (808, N'LL Mountain Handlebars', NULL, 500, 44.5400, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (809, N'ML Mountain Handlebars', NULL, 500, 61.9200, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (810, N'HL Mountain Handlebars', NULL, 500, 120.2700, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (811, N'LL Road Handlebars', NULL, 500, 44.5400, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (812, N'ML Road Handlebars', NULL, 500, 61.9200, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (813, N'HL Road Handlebars', NULL, 500, 120.2700, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (814, N'ML Mountain Frame - Black, 38', N'Black', 500, 348.7600, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (815, N'LL Mountain Front Wheel', N'Black', 500, 60.7450, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (816, N'ML Mountain Front Wheel', N'Black', 500, 209.0250, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (817, N'HL Mountain Front Wheel', N'Black', 500, 300.2150, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (818, N'LL Road Front Wheel', N'Black', 500, 85.5650, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (819, N'ML Road Front Wheel', N'Black', 500, 248.3850, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (820, N'HL Road Front Wheel', N'Black', 500, 330.0600, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (821, N'Touring Front Wheel', N'Black', 500, 218.0100, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (822, N'ML Road Frame-W - Yellow, 38', N'Yellow', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (823, N'LL Mountain Rear Wheel', N'Black', 500, 87.7450, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (824, N'ML Mountain Rear Wheel', N'Black', 500, 236.0250, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (825, N'HL Mountain Rear Wheel', N'Black', 500, 327.2150, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (826, N'LL Road Rear Wheel', N'Black', 500, 112.5650, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (827, N'ML Road Rear Wheel', N'Black', 500, 275.3850, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (828, N'HL Road Rear Wheel', N'Black', 500, 357.0600, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (829, N'Touring Rear Wheel', N'Black', 500, 245.0100, 17)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (830, N'ML Mountain Frame - Black, 40', N'Black', 500, 348.7600, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (831, N'ML Mountain Frame - Black, 44', N'Black', 500, 348.7600, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (832, N'ML Mountain Frame - Black, 48', N'Black', 500, 348.7600, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (833, N'ML Road Frame-W - Yellow, 40', N'Yellow', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (834, N'ML Road Frame-W - Yellow, 42', N'Yellow', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (835, N'ML Road Frame-W - Yellow, 44', N'Yellow', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (836, N'ML Road Frame-W - Yellow, 48', N'Yellow', 500, 594.8300, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (837, N'HL Road Frame - Black, 62', N'Black', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (838, N'HL Road Frame - Black, 44', N'Black', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (839, N'HL Road Frame - Black, 48', N'Black', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (840, N'HL Road Frame - Black, 52', N'Black', 500, 1431.5000, 14)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (841, N'Men''s Sports Shorts, S', N'Black', 4, 59.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (842, N'Touring-Panniers, Large', N'Grey', 4, 125.0000, 35)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (843, N'Cable Lock', NULL, 4, 25.0000, 34)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (844, N'Minipump', NULL, 4, 19.9900, 36)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (845, N'Mountain Pump', NULL, 4, 24.9900, 36)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (846, N'Taillights - Battery-Powered', NULL, 4, 13.9900, 33)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (847, N'Headlights - Dual-Beam', NULL, 4, 34.9900, 33)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (848, N'Headlights - Weatherproof', NULL, 4, 44.9900, 33)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (849, N'Men''s Sports Shorts, M', N'Black', 4, 59.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (850, N'Men''s Sports Shorts, L', N'Black', 4, 59.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (851, N'Men''s Sports Shorts, XL', N'Black', 4, 59.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (852, N'Women''s Tights, S', N'Black', 4, 74.9900, 24)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (853, N'Women''s Tights, M', N'Black', 4, 74.9900, 24)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (854, N'Women''s Tights, L', N'Black', 4, 74.9900, 24)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (855, N'Men''s Bib-Shorts, S', N'Multi', 4, 89.9900, 18)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (856, N'Men''s Bib-Shorts, M', N'Multi', 4, 89.9900, 18)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (857, N'Men''s Bib-Shorts, L', N'Multi', 4, 89.9900, 18)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (858, N'Half-Finger Gloves, S', N'Black', 4, 24.4900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (859, N'Half-Finger Gloves, M', N'Black', 4, 24.4900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (860, N'Half-Finger Gloves, L', N'Black', 4, 24.4900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (861, N'Full-Finger Gloves, S', N'Black', 4, 37.9900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (862, N'Full-Finger Gloves, M', N'Black', 4, 37.9900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (863, N'Full-Finger Gloves, L', N'Black', 4, 37.9900, 20)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (864, N'Classic Vest, S', N'Blue', 4, 63.5000, 25)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (865, N'Classic Vest, M', N'Blue', 4, 63.5000, 25)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (866, N'Classic Vest, L', N'Blue', 4, 63.5000, 25)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (867, N'Women''s Mountain Shorts, S', N'Black', 4, 69.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (868, N'Women''s Mountain Shorts, M', N'Black', 4, 69.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (869, N'Women''s Mountain Shorts, L', N'Black', 4, 69.9900, 22)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (870, N'Water Bottle - 30 oz.', NULL, 4, 4.9900, 28)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (871, N'Mountain Bottle Cage', NULL, 4, 9.9900, 28)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (872, N'Road Bottle Cage', NULL, 4, 8.9900, 28)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (873, N'Patch Kit/8 Patches', NULL, 4, 2.2900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (874, N'Racing Socks, M', N'White', 4, 8.9900, 23)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (875, N'Racing Socks, L', N'White', 4, 8.9900, 23)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (876, N'Hitch Rack - 4-Bike', NULL, 4, 120.0000, 26)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (877, N'Bike Wash - Dissolver', NULL, 4, 7.9500, 29)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (878, N'Fender Set - Mountain', NULL, 4, 21.9800, 30)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (879, N'All-Purpose Bike Stand', NULL, 4, 159.0000, 27)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (880, N'Hydration Pack - 70 oz.', N'Silver', 4, 54.9900, 32)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (881, N'Short-Sleeve Classic Jersey, S', N'Yellow', 4, 53.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (882, N'Short-Sleeve Classic Jersey, M', N'Yellow', 4, 53.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (883, N'Short-Sleeve Classic Jersey, L', N'Yellow', 4, 53.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (884, N'Short-Sleeve Classic Jersey, XL', N'Yellow', 4, 53.9900, 21)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (885, N'HL Touring Frame - Yellow, 60', N'Yellow', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (886, N'LL Touring Frame - Yellow, 62', N'Yellow', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (887, N'HL Touring Frame - Yellow, 46', N'Yellow', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (888, N'HL Touring Frame - Yellow, 50', N'Yellow', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (889, N'HL Touring Frame - Yellow, 54', N'Yellow', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (890, N'HL Touring Frame - Blue, 46', N'Blue', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (891, N'HL Touring Frame - Blue, 50', N'Blue', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (892, N'HL Touring Frame - Blue, 54', N'Blue', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (893, N'HL Touring Frame - Blue, 60', N'Blue', 500, 1003.9100, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (894, N'Rear Derailleur', N'Silver', 500, 121.4600, 9)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (895, N'LL Touring Frame - Blue, 50', N'Blue', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (896, N'LL Touring Frame - Blue, 54', N'Blue', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (897, N'LL Touring Frame - Blue, 58', N'Blue', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (898, N'LL Touring Frame - Blue, 62', N'Blue', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (899, N'LL Touring Frame - Yellow, 44', N'Yellow', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (900, N'LL Touring Frame - Yellow, 50', N'Yellow', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (901, N'LL Touring Frame - Yellow, 54', N'Yellow', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (902, N'LL Touring Frame - Yellow, 58', N'Yellow', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (903, N'LL Touring Frame - Blue, 44', N'Blue', 500, 333.4200, 16)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (904, N'ML Mountain Frame-W - Silver, 40', N'Silver', 500, 364.0900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (905, N'ML Mountain Frame-W - Silver, 42', N'Silver', 500, 364.0900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (906, N'ML Mountain Frame-W - Silver, 46', N'Silver', 500, 364.0900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (907, N'Rear Brakes', N'Silver', 500, 106.5000, 6)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (908, N'LL Mountain Seat/Saddle', NULL, 500, 27.1200, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (909, N'ML Mountain Seat/Saddle', NULL, 500, 39.1400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (910, N'HL Mountain Seat/Saddle', NULL, 500, 52.6400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (911, N'LL Road Seat/Saddle', NULL, 500, 27.1200, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (912, N'ML Road Seat/Saddle', NULL, 500, 39.1400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (913, N'HL Road Seat/Saddle', NULL, 500, 52.6400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (914, N'LL Touring Seat/Saddle', NULL, 500, 27.1200, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (915, N'ML Touring Seat/Saddle', NULL, 500, 39.1400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (916, N'HL Touring Seat/Saddle', NULL, 500, 52.6400, 15)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (917, N'LL Mountain Frame - Silver, 42', N'Silver', 500, 264.0500, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (918, N'LL Mountain Frame - Silver, 44', N'Silver', 500, 264.0500, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (919, N'LL Mountain Frame - Silver, 48', N'Silver', 500, 264.0500, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (920, N'LL Mountain Frame - Silver, 52', N'Silver', 500, 264.0500, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (921, N'Mountain Tire Tube', NULL, 500, 4.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (922, N'Road Tire Tube', NULL, 500, 3.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (923, N'Touring Tire Tube', NULL, 500, 4.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (924, N'LL Mountain Frame - Black, 42', N'Black', 500, 249.7900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (925, N'LL Mountain Frame - Black, 44', N'Black', 500, 249.7900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (926, N'LL Mountain Frame - Black, 48', N'Black', 500, 249.7900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (927, N'LL Mountain Frame - Black, 52', N'Black', 500, 249.7900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (928, N'LL Mountain Tire', NULL, 500, 24.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (929, N'ML Mountain Tire', NULL, 500, 29.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (930, N'HL Mountain Tire', NULL, 500, 35.0000, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (931, N'LL Road Tire', NULL, 500, 21.4900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (932, N'ML Road Tire', NULL, 500, 24.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (933, N'HL Road Tire', NULL, 500, 32.6000, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (934, N'Touring Tire', NULL, 500, 28.9900, 37)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (935, N'LL Mountain Pedal', N'Silver/Black', 500, 40.4900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (936, N'ML Mountain Pedal', N'Silver/Black', 500, 62.0900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (937, N'HL Mountain Pedal', N'Silver/Black', 500, 80.9900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (938, N'LL Road Pedal', N'Silver/Black', 500, 40.4900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (939, N'ML Road Pedal', N'Silver/Black', 500, 62.0900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (940, N'HL Road Pedal', N'Silver/Black', 500, 80.9900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (941, N'Touring Pedal', N'Silver/Black', 500, 80.9900, 13)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (942, N'ML Mountain Frame-W - Silver, 38', N'Silver', 500, 364.0900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (943, N'LL Mountain Frame - Black, 40', N'Black', 500, 249.7900, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (944, N'LL Mountain Frame - Silver, 40', N'Silver', 500, 264.0500, 12)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (945, N'Front Derailleur', N'Silver', 500, 91.4900, 9)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (946, N'LL Touring Handlebars', NULL, 500, 46.0900, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (947, N'HL Touring Handlebars', NULL, 500, 91.5700, 4)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (948, N'Front Brakes', N'Silver', 500, 106.5000, 6)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (949, N'LL Crankset', N'Black', 500, 175.4900, 8)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (950, N'ML Crankset', N'Black', 500, 256.4900, 8)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (951, N'HL Crankset', N'Black', 500, 404.9900, 8)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (952, N'Chain', N'Silver', 500, 20.2400, 7)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (953, N'Touring-2000 Blue, 60', N'Blue', 100, 1214.8500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (954, N'Touring-1000 Yellow, 46', N'Yellow', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (955, N'Touring-1000 Yellow, 50', N'Yellow', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (956, N'Touring-1000 Yellow, 54', N'Yellow', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (957, N'Touring-1000 Yellow, 60', N'Yellow', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (958, N'Touring-3000 Blue, 54', N'Blue', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (959, N'Touring-3000 Blue, 58', N'Blue', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (960, N'Touring-3000 Blue, 62', N'Blue', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (961, N'Touring-3000 Yellow, 44', N'Yellow', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (962, N'Touring-3000 Yellow, 50', N'Yellow', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (963, N'Touring-3000 Yellow, 54', N'Yellow', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (964, N'Touring-3000 Yellow, 58', N'Yellow', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (965, N'Touring-3000 Yellow, 62', N'Yellow', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (966, N'Touring-1000 Blue, 46', N'Blue', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (967, N'Touring-1000 Blue, 50', N'Blue', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (968, N'Touring-1000 Blue, 54', N'Blue', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (969, N'Touring-1000 Blue, 60', N'Blue', 100, 2384.0700, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (970, N'Touring-2000 Blue, 46', N'Blue', 100, 1214.8500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (971, N'Touring-2000 Blue, 50', N'Blue', 100, 1214.8500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (972, N'Touring-2000 Blue, 54', N'Blue', 100, 1214.8500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (973, N'Road-350-W Yellow, 40', N'Yellow', 100, 1700.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (974, N'Road-350-W Yellow, 42', N'Yellow', 100, 1700.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (975, N'Road-350-W Yellow, 44', N'Yellow', 100, 1700.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (976, N'Road-350-W Yellow, 48', N'Yellow', 100, 1700.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (977, N'Road-750 Black, 58', N'Black', 100, 539.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (978, N'Touring-3000 Blue, 44', N'Blue', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (979, N'Touring-3000 Blue, 50', N'Blue', 100, 742.3500, 3)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (980, N'Mountain-400-W Silver, 38', N'Silver', 100, 769.4900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (981, N'Mountain-400-W Silver, 40', N'Silver', 100, 769.4900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (982, N'Mountain-400-W Silver, 42', N'Silver', 100, 769.4900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (983, N'Mountain-400-W Silver, 46', N'Silver', 100, 769.4900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (984, N'Mountain-500 Silver, 40', N'Silver', 100, 564.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (985, N'Mountain-500 Silver, 42', N'Silver', 100, 564.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (986, N'Mountain-500 Silver, 44', N'Silver', 100, 564.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (987, N'Mountain-500 Silver, 48', N'Silver', 100, 564.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (988, N'Mountain-500 Silver, 52', N'Silver', 100, 564.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (989, N'Mountain-500 Black, 40', N'Black', 100, 539.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (990, N'Mountain-500 Black, 42', N'Black', 100, 539.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (991, N'Mountain-500 Black, 44', N'Black', 100, 539.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (992, N'Mountain-500 Black, 48', N'Black', 100, 539.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (993, N'Mountain-500 Black, 52', N'Black', 100, 539.9900, 1)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (994, N'LL Bottom Bracket', NULL, 500, 53.9900, 5)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (995, N'ML Bottom Bracket', NULL, 500, 101.2400, 5)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (996, N'HL Bottom Bracket', NULL, 500, 121.4900, 5)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (997, N'Road-750 Black, 44', N'Black', 100, 539.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (998, N'Road-750 Black, 48', N'Black', 100, 539.9900, 2)
;INSERT INTO adv_product (ProductID, Name, Color, SafetyStockLevel, ListPrice, ProductSubcategoryID) VALUES (999, N'Road-750 Black, 52', N'Black', 100, 539.9900, 2)
